In [30]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
import sklearn.metrics as sklm
import matplotlib.pyplot as plt
from sklearn.inspection import DecisionBoundaryDisplay
import sklearn.inspection

In [31]:
iris_df = pd.read_csv("Iris.csv")
iris_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
for column in iris_df.columns[: -1] :
    fig, ax = plt.sub

In [32]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

> Here Species column is of string type

> Also the Id column is not needed

In [33]:
iris_df.drop(axis=1, columns="Id", inplace=True)

In [34]:
labels = iris_df.iloc[:, -1].unique()
iris_df.replace(
    labels, 
    [i for i in range(len(labels))], 
    inplace=True
)

iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

/tmp/ipykernel_5234/2638819449.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  iris_df.replace(

In [35]:
from sklearn.inspection import DecisionBoundaryDisplay

In [36]:
x, y = iris_df.iloc[:, : -1], iris_df.iloc[:, -1]
x_train, x_test, y_train, y_test  = train_test_split(x, y, random_state=200, test_size=0.3)

kernels = ['linear', 'sigmoid']

C= 1.0
models = [
    svm.SVC(kernel="linear", C=C),
    svm.SVC(kernel="sigmoid", C=C)
]
# training
models[0] = models[0].fit(x_train, y_train)

y_train_sig = y_train
y_train_sig[y_train_sig != 0] = 1

y_test_sig = y_test
y_test_sig[y_test_sig != 0] = 1

models[1] = models[1].fit(x_train, y_train_sig)

# predicting 
y_pred_lin = models[0].predict(x_test)
y_pred_sig = models[1].predict(x_test)

print(y_pred_lin)
print(y_pred_sig, y_test_sig)

[1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1 0 1 1 0 1 0 0
 0 2 1 1 0 0 1 2]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1] 84     1
122    1
28     0
24     0
75     1
109    1
81     1
98     1
80     1
100    1
124    1
2      0
34     0
44     0
128    1
13     0
93     1
41     0
63     1
137    1
19     0
60     1
126    1
11     0
47     0
18     0
96     1
107    1
141    1
53     1
39     0
99     1
92     1
4      0
97     1
48     0
10     0
9      0
127    1
86     1
88     1
12     0
21     0
66     1
113    1
Name: Species, dtype: int64